###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - './app:/application'
        environment:
            - POSTGRES_USER=azkam
            - POSTGRES_PASSWORD=aziz007td
            - POSTGRES_DB=tiwe
        ports:
            - '60004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '60000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
