# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    typesense.host: '%env(TYPESENSE_HOST)%'
    typesense.port: '%env(TYPESENSE_PORT)%'
    typesense.api_key: '%env(TYPESENSE_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Typesense Configuration
    App\Service\TypesenseClientService:
        arguments:
            $typesenseHost: '%typesense.host%'
            $typesensePort: '%typesense.port%'
            $typesenseApiKey: '%typesense.api_key%'
